<?php

namespace AppBundle\Repository;

/**
 * ProfilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilesRepository extends \Doctrine\ORM\EntityRepository
{
}
